#!/bin/sh

if test -e ".env"; then

  . .env
fi

if [ -z "$1" ]; then

  if [ -z "$DEFAULT_COMMIT_MESSAGE" ]; then

    MESSAGE="Auto-commit."

  else

    MESSAGE="$DEFAULT_COMMIT_MESSAGE"
  fi

else

  MESSAGE="$1"
fi

echo "$MESSAGE" && commit "$MESSAGE" && git log -n 1